[project]
name = "webcam-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.128.0",
    "opencv-python>=4.12.0.88",
    "ultralytics>=8.3.243",
    "uvicorn[standard]>=0.40.0",
]
